### ISSUE TITLE
Cloudflare Durable Objects / SvelteKit and WebSocket

### ISSUE THREAD

**Issue by clibequilibrium** [JoshAshby/joshashby.github.io#22]
Hi !

Thank you so much for your post from https://joshisa.ninja/2022/05/18/sveltekit-cloudflare-durable-object-websockets.html  and unpublished one at https://github.com/JoshAshby/joshashby.github.io/blob/fa69dcdd9e9a81c991c702c5335d5251417af1e1/_drafts/sveltekit-durable-objects-continued.md?plain=1#L4

It is very inspiring and has helped me a lot to figure out Durable Objects with SvelteKit. 

However I am stuck, do you happen to know how did you manage to upgrade to websocket connection using just SvelteKit ? I am struggling to understand whethere a client simply sends ``fetch`` and then the server Upgrades the connection with 101 status, or the client uses ``new Socket(ws: )`` protocol to connect? I was not able to make it work locally . If you have any insights I would appreciate it a ton. We are currently having discussion here https://github.com/cloudflare/cloudflare-docs/issues/13062#issuecomment-1953341484

**Comment by JoshAshby** [comment]
Hey @clibequilibrium, sorry for the slow reply, I'm just now seeing this. I'm glad you found something helpful with that post!

For getting the connection, I used `new Socket(ws:)` in the client:

```typescript
// src/routes/index.svelte
// ...
    let ws = new WebSocket(
      "wss://" + window.location.host + "/api/game-rooms/" + roomId + "/websocket"
    )
```

And then this would trigger the hook hack I describe at the end of my post to upgrade the connection through to the durable object. Unfortunately I haven't circled back to that project in a while though (as the 2 year old draft post might show, hah), and I forgot how I was testing this locally. I very well could have skipped local and just been pushing to a preview deployment knowing me and how short lived that project was 🤪.

That's an interesting issue on the cloudflare docs and I'll have to keep an eye on it's development!

**Comment by clibequilibrium** [comment]
> Hey @clibequilibrium, sorry for the slow reply, I'm just now seeing this. I'm glad you found something helpful with that post!
> 
> For getting the connection, I used `new Socket(ws:)` in the client:
> 
> ```ts
> // src/routes/index.svelte
> // ...
>     let ws = new WebSocket(
>       "wss://" + window.location.host + "/api/game-rooms/" + roomId + "/websocket"
>     )
> ```
> 
> And then this would trigger the hook hack I describe at the end of my post to upgrade the connection through to the durable object. Unfortunately I haven't circled back to that project in a while though (as the 2 year old draft post might show, hah), and I forgot how I was testing this locally. I very well could have skipped local and just been pushing to a preview deployment knowing me and how short lived that project was 🤪.
> 
> That's an interesting issue on the cloudflare docs and I'll have to keep an eye on it's development!

Thank you for your reply ! Yea I am still surprised you got it working !

Locally it never worked for me because SvelteKit + VIte do not upgrade protocol by default, however even when I deployed my page to Cloudflare it still didn't work.  

So I just deployed Durable Object with a worker that is designed specifically to upgrade the protocol to Websocket. Your blog series helped me a lot ! I also got a perfect wrangler dev setup for the Durable Object working with hot reload. I connect locally to the websocket server and I am loving how quickly I am iterating with SvelteKit + Durable Objects.

Thank you again for the write up and the response.
